### ISSUE TITLE
hexmap fails

### ISSUE THREAD

**Issue by iancrossfield** [lifelike/hexmapextension#32]
When I try to use the Hexmap extension with its default settings, I get the following error message:

Traceback (most recent call last):
  File "hexmap.py", line 509, in <module>
    effect.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 285, in affect
    self.output()
  File "/usr/share/inkscape/extensions/inkex.py", line 272, in output
    self.document.write(sys.stdout)
  File "src/lxml/etree.pyx", line 2056, in lxml.etree._ElementTree.write
  File "src/lxml/serializer.pxi", line 758, in lxml.etree._tofilelike
  File "src/lxml/etree.pyx", line 318, in lxml.etree._ExceptionContext._raise_if_stored
  File "src/lxml/serializer.pxi", line 682, in lxml.etree._FilelikeWriter.write
TypeError: write() argument must be str, not bytes

**Comment by lifelike** [comment]
What version of inkscape? What version of the hexmap extension?

Can you run other inkscape extensions (having the exact same drawing open as when you tried to run the hexmap extension)?
